# Generated by Django 5.0.1 on 2024-01-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_country_alter_customer_createat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/customers'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='doc_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/doc'),
        ),
    ]
