# Generated by Django 5.0.1 on 2024-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_photo_alter_customer_doc_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc_upload',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/doc'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/customers'),
        ),
    ]
