# Generated by Django 5.0.1 on 2024-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_gender_alter_customer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JEupload', models.FileField(blank=True, null=True, upload_to='static/uploads/JE')),
            ],
        ),
    ]
