# Generated by Django 5.0.1 on 2024-04-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_status_and_more'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.gstatus'),
        ),
    ]
