# Generated by Django 5.0.1 on 2024-01-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refname', models.CharField(max_length=150)),
                ('display', models.CharField(max_length=150)),
                ('refmobile', models.IntegerField(max_length=10)),
                ('refphone', models.IntegerField(max_length=10)),
                ('refemail', models.EmailField(max_length=10)),
                ('refregister', models.CharField(max_length=10)),
                ('refspeciality', models.CharField(max_length=10)),
                ('refaddress', models.CharField(max_length=250)),
                ('refstate', models.CharField(max_length=100)),
                ('refcountry', models.CharField(max_length=100)),
                ('refpincode', models.IntegerField(max_length=10)),
                ('refdob', models.DateField(blank=True, null=True)),
                ('refdoa', models.DateField(blank=True, null=True)),
                ('refpricelist', models.CharField(max_length=10)),
                ('refreport', models.BooleanField(default=False)),
                ('refcreateat', models.DateTimeField(auto_now_add=True)),
                ('refupdateat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
