# Generated by Django 5.0.1 on 2024-01-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refdoctor',
            old_name='refcreateat',
            new_name='createat',
        ),
        migrations.RenameField(
            model_name='refdoctor',
            old_name='refupdateat',
            new_name='updateat',
        ),
    ]
