# Generated by Django 5.0.1 on 2024-01-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docters', '0002_rename_refcreateat_refdoctor_createat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refdoctor',
            old_name='createat',
            new_name='refcreateat',
        ),
        migrations.RenameField(
            model_name='refdoctor',
            old_name='updateat',
            new_name='refupdateat',
        ),
    ]
